---
AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
  - bin/**/*
  - vendor/**/*
  ExtraDetails: true
  TargetRubyVersion: 3.4
  UseCache: true
inherit_mode:
  merge:
  - Exclude
plugins:
- rubocop-rake
- rubocop-rspec
require: []
inherit_from:
  - .rubocop_todo.yml
  - .rubocop/bundler.yml
  - .rubocop/gemspec.yml
  - .rubocop/layout.yml
  - .rubocop/lint.yml
  - .rubocop/metrics.yml
  - .rubocop/migration.yml
  - .rubocop/naming.yml
  - .rubocop/rspec.yml
  - .rubocop/rake.yml
  - .rubocop/security.yml
  - .rubocop/style.yml

RSpec/ExampleLength:
  Exclude:
    - 'spec/exprify/parser_spec.rb'

# Parser class handles complex parsing logic and requires significant complexity
# to properly implement the search expression grammar.
Metrics/AbcSize:
  Exclude:
    - 'lib/exprify/parser.rb'

# Parser class needs to handle various parsing cases and maintain state,
# resulting in a necessarily larger class size.
Metrics/ClassLength:
  Exclude:
    - 'lib/exprify/parser.rb'

# Parser methods involve multiple conditional branches to handle different
# token patterns and expression types.
Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/exprify/parser.rb'

# AST and Parser methods need to handle complex logic that cannot be
# meaningfully split into smaller methods without sacrificing clarity.
#
# The pretty_print_children method in Node class requires a specific structure
# to properly handle indentation, line breaks, and comma placement for
# pretty printing AST nodes. Breaking it into smaller methods would make
# the printing logic harder to follow and maintain.
Metrics/MethodLength:
  Exclude:
    - 'lib/exprify/ast.rb'
    - 'lib/exprify/parser.rb'
    - 'lib/exprify/ast/node.rb'

# Parser methods require multiple condition checks and branching paths
# to properly handle the parsing logic.
Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/exprify/parser.rb'
